### ISSUE TITLE
does this work yet?

### ISSUE THREAD

**Issue by jackttcoms** [mcoudurier/simple-MVC-blog#1]
Hi i attempted to use it on my localhost but nothing is working so i was wondering whether this actually works yet?

Thanks

**Comment by mcoudurier** [comment]
Hello. Yes, it works. You can see it running there: http://projet4.mathieucoudurier.com
If you tell me what kind of error you are getting, I'll look into it.

**Comment by jackttcoms** [comment]
What is the login credentials for the demo? And i will send you the error i get in a bit!

Thanks

**Comment by mcoudurier** [comment]
Credentials are not provided with the demo.

**Comment by jackttcoms** [comment]
how about a register form?

**Comment by mcoudurier** [comment]
Best I can do right now is add a default password to the database.sql file.

**Comment by jackttcoms** [comment]
yes can you do that please and also basically the error is the script does not load! I have changed the database file data and renamed it database.php and i cant see any other config options so it does not wanna work!

Let me know if i have forgotten something.

Thanks

**Comment by mcoudurier** [comment]
No output? Just straight doesn't load? Must be something wrong with your setup then.
